### ISSUE TITLE
DrawPath feature not working on ReactNative

### ISSUE THREAD

**Issue by akaipham** [Hopding/react-native-pdf-lib#1]
AbstractContentContext::GraphicOptions pathStrokeOptions(
AbstractContentContext::eStroke,
AbstractContentContext::eRGB,
AbstractContentContext::ColorValueForName("DarkMagenta"),
4);

DoubleAndDoublePairList pathPoints;

// draw path
pathPoints.push_back(DoubleAndDoublePair(100,200));
pathPoints.push_back(DoubleAndDoublePair(100,201));
pathPoints.push_back(DoubleAndDoublePair(100,202));
context->DrawPath(pathPoints,pathStrokeOptions);
I've followed above snippet as https://github.com/galkahana/PDF-Writer/blob/master/PDFWriterTestPlayground/HighLevelContentContext.cpp#L64. But it didn't display any path. I tried with DrawCircle, DrawSquare and all worked well except DrawPath.

Is it possible to use `DrawPath` on RN?

**Comment by Hopding** [comment]
I take it that you are attempting to modify the actual native code for iOS? In that case, it should be possible to use any functionality that exists in the `PDF-Writer`, within RN. 

One possibility is that the static binaries this project uses were built prior to the addition of `DrawPath`. I can look into that this weekend.

Sorry for that late reply.

**Comment by Hopding** [comment]
I just tested out the code sample you provided. I modified the [`applyActions`](https://github.com/Hopding/react-native-pdf-lib/blob/master/ios/PDFPageFactory.mm#L41-L54) method to run the following snippet every time it is executed (so, for every page that is added to a PDF using the JavaScript API).
[test.pdf](https://github.com/Hopding/react-native-pdf-lib/files/1325984/test.pdf)

```c++
AbstractContentContext::GraphicOptions pathStrokeOptions(
                                                        AbstractContentContext::eStroke,
                                                        AbstractContentContext::eRGB,
                                                        AbstractContentContext::ColorValueForName("DarkMagenta"),
                                                        4);
    
DoubleAndDoublePairList pathPoints;
    
// draw path
pathPoints.push_back(DoubleAndDoublePair(100,200));
pathPoints.push_back(DoubleAndDoublePair(100,210));
pathPoints.push_back(DoubleAndDoublePair(115,215));
context->DrawPath(pathPoints,pathStrokeOptions);
```

This seems to have worked. Running the following JavaScript code produced the attached PDF file, which does contain lines as a result of calling `DrawPath`.
```javascript
const dir = await PDFLib.getDocumentsDirectory();

const page1 = PDFPage
  .create()
  .setMediaBox(250, 500)
  .drawText('This is a test...', {
    x: 5,
    y: 490,
    color: '#800000',
    fontSize: 15,
  });

PDFDocument
  .create(`${dir}/test.pdf`)
  .addPages(page1)
  .write();
```
