### ISSUE TITLE
Cannot Read propertly getDocumentsDirectory of undefined

### ISSUE THREAD

**Issue by ivanxtr** [Hopding/react-native-pdf-lib#14]
createPDF(){

        const page1 = PDFPage
            .create()
            .setMediaBox(200, 200)
            .drawText('You can add text and rectangles to the PDF!', {
                x: 5,
                y: 235,
                color: '#007386',
            })
            .drawRectangle({
                x: 25,
                y: 25,
                width: 150,
                height: 150,
                color: '#FF99CC',
            })
            .drawRectangle({
                x: 75,
                y: 75,
                width: 50,
                height: 50,
                color: '#99FFCC',
            });

        const jpgPath = "/Users/jorgerodriguez/Library/Developer/CoreSimulator/Devices/6DC98194-6397-49CF-80AA-D12141135B72/data/Containers/Data/Application/12D943E7-9F92-4CED-9731-6862F6AC86F8/Documents/009AA984-0B1C-421D-9DF9-1380B39737E8.jpg";
        const page2 = PDFPage
            .create()
            .setMediaBox(250, 250)
            .drawText('You can add JPG images too!')
            .drawImage(jpgPath, 'jpg', {
                x: 5,
                y: 125,
                width: 200,
                height: 100,
            })

        const docsDir = PDFLib.getDocumentsDirectory();
        const pdfPath = `${docsDir}/sample.pdf`;
        PDFDocument
            .create(pdfPath)
            .addPages(page1, page2)
            .write() // Returns a promise that resolves with the PDF's path
            .then(path => {
                console.log('PDF created at: ' + path);
                // Do stuff with your shiny new PDF!
            });
    }

![image](https://user-images.githubusercontent.com/32345257/37044010-eae09544-2127-11e8-8ac5-c0fe47e21221.png)

**Comment by ivanxtr** [comment]
i've solved this one:
closing the simulator and restarting again the simulator

**Comment by Sata51** [comment]
You are using 
`const docsDir = PDFLib.getDocumentsDirectory();`
The  `PDFLib.getDocumentsDirectory();` method return a promise.

In documentation, the implementation is using `await` like this:
`const docsDir = await PDFLib.getDocumentsDirectory();`

**Comment by Rahish** [comment]
const docsDir = await PDFLib.getDocumentsDirectory();

I have used same like above but still getting same issue only for iOS. For ANdroid its working fine. Can you please suggest any Solution.
