### ISSUE TITLE
Error generating PDF 

### ISSUE THREAD

**Issue by ivanxtr** [Hopding/react-native-pdf-lib#15]
![image](https://user-images.githubusercontent.com/32345257/37044233-92b53338-2128-11e8-9b50-b28b36831dd8.png)

**Comment by Hopding** [comment]
Need more information to help you with this.

My apologies for the late response. I'm going to close this for now. Bu, please feel free to re-open it if you're still encountering this issue.

**Comment by Chetanspace** [comment]
i am facing same issue

**Comment by ankii9600** [comment]
I am facing same issue when adding more than one pages ...

**Comment by ankii9600** [comment]
![issue opening](https://user-images.githubusercontent.com/13003611/48659396-4fc2b100-ea76-11e8-8289-5ca038208b2e.png)

**Comment by ankii9600** [comment]
I got it only breaks when it has image type of png.. i thibnk only jpg images are supported ..

**Comment by Chetanspace** [comment]
yeah that why i used base64 image for rendering and it worked for me
