### ISSUE TITLE
For Android method PDFPage.drawImage doesn't work

### ISSUE THREAD

**Issue by ll-upwork** [Hopding/react-native-pdf-lib#18]
When I try to modify pdf and use method  PDFPage.drawImage(pathToJpg, 'jpg') I get error` [Android] Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference`
Without PDFPage.drawImage everything is working

**Comment by Hopding** [comment]
I'm going to close this issue. Please feel free to reopen it if you'd like to continue discussion.

**Comment by Chetanspace** [comment]
facing same issue !!

**Comment by SiSa68** [comment]
Had same issue, and I fix it by removing 'file://' from the beginning of the image path
`.drawImage(jpgPath.replace('file://',''), 'jpg', ...`
