### ISSUE TITLE
Couldn't make drawImage work

### ISSUE THREAD

**Issue by felippepuhle** [Hopding/react-native-pdf-lib#19]
```
  const page = PDFPage.create()
    .setMediaBox(200, 100)
    .drawImage('../assets/logo.png', 'png', {
      x: 0,
      y: 0,
      width: 200,
      height: 100,
    });
```

<img width="388" alt="screen shot 2018-04-25 at 5 41 33 pm" src="https://user-images.githubusercontent.com/15961929/39271619-ed76d0de-48af-11e8-8966-8dd2232383fa.png">

What am I doing wrong?

**Comment by Hopding** [comment]
Unfortunately relative file paths like you're using will not work. You must specify an absolute path to an image on the device's file system. 

So, if you have an image called `logo.png` located under the documents directory of the device, you can obtain its absolute path like so:
```javascript
const docsDir = await PDFLib.getDocumentsDirectory();
const logoPath = `${docsDir}/logo.png`;
```

The issue in your case will be how to get your logo into the documents directory of the device. The easiest way to do this that I can think of is:
1. Convert your image to a base64 string and store that in a JavaScript variable. 
2. Use [`RNFS.writeFile`](https://github.com/itinance/react-native-fs#writefilefilepath-string-contents-string-encoding-string-promisevoid) to save the image to the device's file system.
3. Now you can get it's absolute path (as shown above) and embed it in the PDF.

Here's a quick example:
```javascript
const docsDir = await PDFLib.getDocumentsDirectory();
const base64Image = '<OMITTED>';
const imagePath = `${docsDir}/logo.png`

await RNFS.writeFile(imagePath, base64Image, 'base64');
const page = PDFPage.create()
    .setMediaBox(200, 100)
    .drawImage(path, 'png', {
      x: 0,
      y: 0,
      width: 200,
      height: 100,
    });
```

**NOTE:** To convert your image to a base64 string, you can use a site like this: https://www.base64-image.de/. Or, if you have access to a bash shell, you can just run this command: `cat ./assets/logo.png | base64`. This will print the base64 version of your image to stdout.

**Comment by felippepuhle** [comment]
Thanks, @Hopding! 😄
