### ISSUE TITLE
[iOS] BAD_ACCESS_MEMORY

### ISSUE THREAD

**Issue by FlaviooLima** [Hopding/react-native-pdf-lib#20]
Manual instructions are incorrect only `react-native link` works.

Android:
import com.reactlibrary.PdfLibPackage; -> import com.hopding.pdflib.PDFLibPackage;
new PdfLibPackage() -> new PDFLibPackage();

iOS: Don't know how it should be, but the usual manual link don't work.

**Comment by Korno91** [comment]
Yeh exactly, wasted a lot of time on that

**Comment by Hopding** [comment]
@FlaviooLima Just to make sure I understand: You tried installing `react-native-pdf-lib` using the [manual instructions](https://github.com/Hopding/react-native-pdf-lib#manual-installation), but when you ran the example on iOS after doing so, you got a `BAD_ACCESS_MEMORY` error? And after running `react-native link`, it worked fine?

**Comment by FlaviooLima** [comment]
@Hopding Exactly. 
I didn't change the title because of people like @Korno91 and me that thought the bad access was a bug from the package instead a of a bad linking.
Manual linking doesn't work on iOS and in android the instructions are incorrect.
Could you test the manual linking to check if it happens to you?

PS: Side problem (if you want i can open a separate issue).

**Comment by Hopding** [comment]
I think the linking issue may be related to the Times New Roman font included in the `/assets` directory. I'll try to take a look this weekend and update the code or the README instructions.

**Comment by FlaviooLima** [comment]
Hi, thanks for the response :)
Since there is no more reason to leave it open i´m gonna close it :)
