### ISSUE TITLE
Can't add images

### ISSUE THREAD

**Issue by FlaviooLima** [Hopding/react-native-pdf-lib#22]
Can't add images.
I'm i doing it wrong?  
It happens to png and jpeg when i try to modify and create a pdf. 

iOS shows yellow warning "Error modifying PDF!"
Android shows:
![screen shot 2018-06-28 at 17 59 50](https://user-images.githubusercontent.com/13239857/42049166-120a99ec-7afd-11e8-87b6-faf669fc3573.png)

```
 const docsDir = await PDFLib.getDocumentsDirectory();

 const base64Image = "data:image/jpeg;base64,****RESTOFBASE64****"

 const logo = `${docsDir}/report.jpg`;

 await RNFS.writeFile(logo, base64Image, 'base64');

 .drawImage(logo, 'jpg', {
 x: 125,
 y: 125,
 width: 200,
 height: 200,
})
```

**Comment by Hopding** [comment]
It looks like the problem might be that you are saving a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) as the JPG file, rather than just the base64 image data. 

Try the following:
```javascript
 const docsDir = await PDFLib.getDocumentsDirectory();

 // Omit the "data:image/jpeg;base64," prefix:
 const base64Image = "****RESTOFBASE64****"

 const logo = `${docsDir}/report.jpg`;

 await RNFS.writeFile(logo, base64Image, 'base64');

 .drawImage(logo, 'jpg', {
   x: 125,
   y: 125,
   width: 200,
   height: 200,
 })
```

**Comment by FlaviooLima** [comment]
Hi, thanks for the response but i´m not working any more at the project so i can´t test it.
I´m gonna believe that i did some mistake and you gave the right answer so i´m gonna  close it.
