### ISSUE TITLE
No podspec found for `RNReactNativePdfLib` in `../node_modules/react-native-pdf-lib`

### ISSUE THREAD

**Issue by VanessaChu** [Hopding/react-native-pdf-lib#24]
Tried to add podspec to my podfile 

  pod 'RNReactNativePdfLib', :path => ‘../node_modules/react-native-pdf-lib'

but received this error on pod install
[!] No podspec found for `RNReactNativePdfLib` in `../node_modules/react-native-pdf-lib`

**Comment by jackdewhurst** [comment]
I had the same problem using latest versions of React Native and this library.. I've forked it here https://github.com/jackdewhurst/react-native-pdf-lib, modified the podspec and added it to the project root. Seems to work now.
