### ISSUE TITLE
PDFLib is not getting exported

### ISSUE THREAD

**Issue by Louies89** [Hopding/react-native-pdf-lib#28]
Hi,
I am using react-native-pdf-lib@0.2.0 with react-native 0.54.

The problem is that PDFLib is not getting exported from native module. And when I am doing 

> alert(PDFLib)

, it shows 

> undefiend

I do not know why it is not imported from native modules. And I was just running your example "**Create a New PDF Document**", each time, I run it it throws error: 

> undefiend not an object (evaluating '_PDFLib2.default.createPDF') 

Please help me to resolve this issue.

**Comment by Hopding** [comment]
Hello @Louies89. Have you linked the module?
```
react-native link react-native-pdf-lib
```

**Comment by Louies89** [comment]
yes I have linked

**Comment by Louies89** [comment]
ooh my god, I had changed

>  include ':app'
to something else, in my settings.gradle, it created all the problem.

whole day is wasted, :(

**Comment by Hopding** [comment]
Well, I'm glad you were able to fix the issue! I feel your pain though. Mess up one part of all that config code and stuff just starts breaking. It's a real time sink.
