### ISSUE TITLE
"Error modifying PDF" can't modify my blank pdf

### ISSUE THREAD

**Issue by njoye** [Hopding/react-native-pdf-lib#29]
Hi,
I have a react native project that builds and works fine. The Library is properly included and creating the modified pages (as described in the readme) works fine. But as soon as I try to use `PDFDocument.write()` I get the error: `Error modifying PDF!`.
I really don't know what to do now, as the error message is not really helpful. Digging through Objective-C Code didn't help much as well. If anyone has an idea where the problem could be, please help. This is my code:

` // Get the blank pdf 
        const pdfPath = "blank.pdf"
        
        // Modify first page in document
        const page1 = PDFPage
        .modify(0)
        .drawText('This is a modification on the first page!', {
            x: 5,
            y: 235,
            color: '#F62727',
        })
        .drawRectangle({
            x: 150,
            y: 150,
            width: 50,
            height: 50,
            color: '#81C744',
        });

        doc = PDFDocument.modify(pdfPath)
        doc = doc.modifyPage(page1)
        doc.write().then( (path) => {console.warning("WORKED GREAT")},
                           (error) => {console.error("Nope: " + error)}         )`

The `blank.pdf` and the file that holds the above code are in the same directory.

**Comment by njoye** [comment]
It seems like this is a writing / reading issue. Trying to simply generating a PDF and saving it into the App's document folder works fine. I'll post my solution once I figured this out.

**Comment by Hopding** [comment]
`react-native-pdf-lib` can only read/write files from the file system. So your `blank.pdf` will need to be placed there before you can do anything with it. One way to do this would be to include it as an asset and then write that asset to the file system at runtime. I think React Native's packager supports adding assets to your app. Though I'm not sure about writing them to the file system.

**Comment by Hopding** [comment]
This article explains how to add a custom font asset: https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e. I imagine you could use a similar approach for a PDF asset. You might be able to use the [`fs.asset`](https://github.com/wkh237/react-native-fetch-blob/wiki/File-System-Access-API#assetfilenamestringstring) method of `rn-fetch-blob` to write the asset to the file system.

**Comment by njoye** [comment]
I've already added the pdf as an asset to the system but that didn't change anything. I guess adding the asset is just one part and writing it to the file system is the second that needs to be done. Then loading it from the apps data directory will probably be solution. Going to post an update as soon as I get to implement that.

**Comment by Hopding** [comment]
@njoye Any updates on this?

**Comment by njoye** [comment]
Not yet as I couldn’t work on it since then. Try writing the file into the app’s data directory when running it (maybe only the first time ?) and then simply access it. That’d be my solution.

**Comment by psyzz** [comment]
@njoye did you found a solution to add the pdf to edit in the app's data directory ?

**Comment by njoye** [comment]
Since I only needed a blank PDF that would then be filled with data, I tried to do everything on a new page inside a new PDF file that was created by `react-native-pdf-lib`. That worked quite well for me.

But I also couldn't work on it anymore, since the project was discontinued so ...
