### ISSUE TITLE
Combine PDFs?

### ISSUE THREAD

**Issue by ddaeschler** [Hopding/react-native-pdf-lib#3]
Good morning,

Is there currently a combination of methods I can use in this library to combine multiple PDF files into a single file?

**Comment by Hopding** [comment]
@ddaeschler The JavaScript API does not currently support this. However, it is possible to add support for this type of thing, as the underlying libraries that are used to manipulate PDFs on Android and iOS support this operation. If you decide to tackle this, please let me know how it goes!

#### Android
It should be possible to use the [`PDFMergerUtility`](https://github.com/TomRoush/PdfBox-Android/blob/2bfdf018e33c7384fbc31ace3126bb320334c61e/library/src/main/java/com/tom_roush/pdfbox/multipdf/PDFMergerUtility.java) class as described [here](https://stackoverflow.com/questions/3585329/how-to-merge-two-pdf-files-into-one-in-java).

#### iOS
The process is described [here](http://pdfhummus.com/post/45501625441/version-17-links-and-merging-pages).

**Comment by ddaeschler** [comment]
Going to start work on this today, and I'll submit a PR.

Thanks!

**Comment by ddaeschler** [comment]
Unfortunately even after implementing this, there seems to be a bug in the PDF library this library depends on:  https://github.com/TomRoush/PdfBox-Android/issues/133

**Comment by ddaeschler** [comment]
I didn't have time to track down the issue in PdfBox, so I opted to use image insertion to generate the PDFs instead which was luckily and option for me. I'll try to keep tracking the PdfBox project incase they issue a fix then I can complete this work.

**Comment by Hopding** [comment]
@ddaeschler Thanks for looking into this 👍

**Comment by thekevinbrown** [comment]
@ddaeschler If you're still facing this, I've got a local implementation that works on both iOS and Android which should be making its way into this library soon.

**Comment by thekevinbrown** [comment]
I'll continue to push to integrate the merger I've built. I'll go ahead and close this issue for now.

**Comment by prathammehta** [comment]
@thekevinbrown any idea if the merger you’ve built has been integrated? If not, is there anywhere I can access your implementation of this? Thanks.

**Comment by thekevinbrown** [comment]
Hey @prathammehta, it's not integrated, and I have not yet received permission to open source the implementation. Sorry. :-(

On iOS it uses CoreGraphics, and on Android it uses com.tom_roush.pdfbox.multipdf.PDFMergerUtility.

**Comment by shandilya1998** [comment]
Hey I am in need of the pdf combining feature. Are you planning to open source it soon or should I go ahead and develop it? I am assuming it will take me around a month for me to get a prototype working on both iOS and android. Would really be frustrating it if you ended up open sourcing it before i completed it.
