### ISSUE TITLE
Removing unnecessary assets from PdfBox-Android

### ISSUE THREAD

**Issue by Louies89** [Hopding/react-native-pdf-lib#31]
Hi @Hopding ,
In ..<App_Name>\android\app\build\intermediates\assets\debug\com\tom_roush, there are lot of resorce files kept for PdfBox-Android library.

As I am using my own costume font and all the resources placed here are can be excluded, otherwise the pdf lib asset size shall be around 9 Mb.

Check below pic, its from my apk:

![image](https://user-images.githubusercontent.com/30086899/47589237-2e463c00-d986-11e8-9c5e-014bcd24c104.png)

Can we have some settings to exclude these, without impacting the library?

**Comment by Louies89** [comment]
@Hopding Will you please help me to integrate the AAR file generated at "https://github.com/tripplemac/pdfbox-android-lite" to integrate with your project.

I wanted to keep the AAR file as a local AAR file and integrate to your library.

I have already spent 15 hours and gone through almost all solutions provided by stackoverflow and other sites. But I am unable to integrate the pdfbox-android-lite to your project.

It will be a great help for me.

Please help me.

**Comment by Louies89** [comment]
@Hopding 
Hi, I was out for a long time, today I saw your reply.

As per your 1st question, `pdfbox-android-lite` does not have any maven or other repository, so I was unable to add dependency, also I dont know how to add another project directly to your library. so I didn't get success.

And about deleting resources, I did not get proper syntax while trying. When I will get some free time, I will try the examples reference you have given.

What I did is , I took the code of `pdfbox-android-lite`  and merged to your library code. It is working, by twerking, few lines of code.

But It will be more appropriate, if info regarding the apk size and how to delete the resources using build.gradle file shall be mentioned in documentation.

**Comment by Hopding** [comment]
@Louies89 I'm certainly open to giving users of `react-native-pdf-lib` more information. It'd be great if you are able to add a section to the README explaining (1) that `PdfBox-Android` is a rather large library, and (2) the steps that can be taken to swap it out. 

I don't think I want to replace `PdfBox-Android` as the default dependency for `react-native-pdf-lib` on Android. But I'm willing to make some code changes to allow users to opt for `pdfbox-android-lite` instead (perhaps a switch variable in the `build.gradle` file?). If you can submit a PR, or share some exact details on what you changed, I'd be grateful.

**Comment by Louies89** [comment]
Sorry to say that, I cannot start a PR, but definitely I can explain what I did, to use `pdfbox-android-lite` with your library. 
1> Compared code, of `PdfBox-Android` & `pdfbox-android-lite` and got to know, some security related files which uses `spongycastle` are removed.
2> As I am not using the sceurity features of PDF, its OK for me, if I will not have those files.
3> `PdfBox-Android` is a complete library to support multiple languages and fonts. So it carries a lot of resources. So as I am using my own font file and English as the default language. those resources are not required. And `pdfbox-android-lite` carries only one resource file. 
4> Now I copied the all codes from `pdfbox-android-lite` and merged with `react-native-pdf-lib`, then imported the modules accordingly. Please refer to the below picture.
![image](https://user-images.githubusercontent.com/30086899/48958582-10b8c200-ef86-11e8-9477-f799b220de9d.png)

5> Kept the resource as per the `pdfbox-android-lite`

**Comment by Louies89** [comment]
But there is a another shortcut, which I tried for 2 days, but didn't get any fruitful result, as Build Gradle set up I didn't get correctly.

The shortcut is :
Including [pdfbox-android-lite-1.8.9.1.aar](https://github.com/tripplemac/pdfbox-android-lite/blob/master/library/release/org/apache/pdfbox-android-lite/1.8.9.1/pdfbox-android-lite-1.8.9.1.aar) directly to the dependency in build gradle file.
