### ISSUE TITLE
how to put a line breaker in drawText, 

### ISSUE THREAD

**Issue by paddy57** [Hopding/react-native-pdf-lib#35]
If the length of question is long enough that text is not visibile how to make the remainig text to be on next line ?

**Comment by Hopding** [comment]
@paddy57 sorry for the late response. @aureliopetrone is correct. PDFs have no notion of line breaks or special control characters like `\n` or `\r`. You'll have to manually figure out when to break your text onto a new line. The [`measureText`](https://github.com/Hopding/react-native-pdf-lib#measuring-text) method should help with this.
