### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ShridharCodewave** [Hopding/react-native-pdf-lib#37]
I tried to create a pdf file using the sample code given. 

 const docsDir = PDFLib.getDocumentsDirectory();
        const pdfPath = `${docsDir}/sample.pdf`;
        PDFDocument
            .create(pdfPath)
            .addPages(page1)
            .write() // Returns a promise that resolves with the PDF's path
            .then(path => {
                alert(path)
                // Do stuff with your shiny new PDF!
            })
            .catch(error => {
                console.error(error);
            });

But Iam getting an error saying
 Error: [object Object]/sample.pdf (No such file or directory)

**Comment by Laurein** [comment]
Have you solved the problem?

**Comment by ShridharCodewave** [comment]
Yes the path given to create the pdf file was causing  the error. I used the download folder to save the pdf which solved the problem.
`PDFDocument
     .create('/storage/emulated/0/Download/sample.pdf')
     .addPages(page1)
     .write() // Returns a promise that resolves with the PDF's path
     .then(path => {
     });`
