### ISSUE TITLE
Is it possible to save pages out of a PDF as images?

### ISSUE THREAD

**Issue by Jorenm** [Hopding/react-native-pdf-lib#4]

**Comment by Hopding** [comment]
@Jorenm The JavaScript API for this library does not currently support this. However, the [Android api](https://github.com/TomRoush/PdfBox-Android) that this library uses to handle PDFs on Android might be able to support it (see [this](https://github.com/TomRoush/PdfBox-Android/blob/1ee740d3739f23d00efaadbf5a83b765e96a29c1/library/src/main/java/com/tom_roush/pdfbox/rendering/PDFRenderer.java#L21) class).

The [library](https://github.com/galkahana/HummusJS) that is (primarily) used by this library to handle PDFs on iOS [does not](https://github.com/galkahana/HummusJS/issues/58) support this. However, you may still be able to implement it on iOS [using the `ImageIO` framework](https://stackoverflow.com/a/6088649).

**Comment by thekevinbrown** [comment]
@Jorenm what's your use case? If it's to preview the PDF pages we've actually built a React Native component where you pass it a PDF path and a page number and it draws the page. This works on both iOS and Android.

Let me know if that'd be helpful.

**Comment by thekevinbrown** [comment]
I'll go ahead and assume this is resolved at this point. If that's not the case please feel free to open a new issue with details.
