### ISSUE TITLE
Generating an index for an unknown number of pages

### ISSUE THREAD

**Issue by jacargentina** [Hopding/react-native-pdf-lib#42]
I'm using [PDFKit](http://pdfkit.org/) on nodeJS; there i can generate a index on start, then add many pages, and go back to the first(S) pages (the index) to write the corresponding page number.

In react-native-pdf-lib is it possible? OR should i create, and then modify the document?

**Comment by Hopding** [comment]
Hello @jacargentina!

This is not currently possible. You'll have to create and then modify the document, as you mentioned.

That being said, I think it would be relatively straightforward to implement support for this. The reason it is not currently possible is that the [`create`](https://github.com/Hopding/react-native-pdf-lib/blob/master/android/src/main/java/com/hopding/pdflib/factories/PDDocumentFactory.java#L32) method only invokes the `addPages` method. But it could be modified to work more like the [`modify`](https://github.com/Hopding/react-native-pdf-lib/blob/master/android/src/main/java/com/hopding/pdflib/factories/PDDocumentFactory.java#L41) method, by calling both `addPages` and `modifyPages`.
