### ISSUE TITLE
How can I see the generated PDF?

### ISSUE THREAD

**Issue by EmmanuelID** [Hopding/react-native-pdf-lib#43]
I have the path but I do not know how to see the PDF

**Comment by Hopding** [comment]
I'd suggest the [`react-native-pdf`](https://github.com/wonday/react-native-pdf) library. It's supposed to support PDF rendering for both Android and iOS. I've personally found it only works well on Android though. I'd recommend [`react-native-webview`](https://github.com/react-native-community/react-native-webview) for iOS.

**Comment by EmmanuelID** [comment]
Thanks 👍

**Comment by lylest** [comment]
i know the path but where is it on my device computer?/
