### ISSUE TITLE
Size unit

### ISSUE THREAD

**Issue by thecoderformerlyknownasprince** [Hopding/react-native-pdf-lib#45]
It looks like the size unit for setMediaBox() is points, which is not mentioned in the readme file. Is that correct?

**Comment by Hopding** [comment]
Hello @thecoderformerlyknownasprince!

You are correct. In all new PDF documents you create with `react-native-pdf-lib` (and in _most_ documents you may wish to modify), the default unit size is 1/72 inch (usually considered to be the size of a [point](https://en.wikipedia.org/wiki/Point_(typography))).
