### ISSUE TITLE
Is there any documentation for the available methods, etc.?

### ISSUE THREAD

**Issue by robinpaulson** [Hopding/react-native-pdf-lib#47]
I see from examining the examples that there are a number of object types available, including:
setMediaBox
drawText
drawRectangle
drawImage

Is there documentation anywhere, to know the full parameters each takes?

**Comment by thekevinbrown** [comment]
The best docs that seem to exist at the moment are the flow types here:

https://github.com/Hopding/react-native-pdf-lib/blob/master/js/src/PDFPage.js

**Comment by thekevinbrown** [comment]
I'll go ahead and assume this is resolved. If not, we welcome contributions of better docs.
