### ISSUE TITLE
Slow operation on Android

### ISSUE THREAD

**Issue by thecoderformerlyknownasprince** [Hopding/react-native-pdf-lib#48]
On iOS PDFs are generated in 1-2 seconds, but on Android it can take literally minutes. Is this a known issue?

**Comment by Beeltec** [comment]
Hi!

I just ran into the same problem with React Native 0.60.4. Turns out, the new Hermes JS-runtime seems to cause these slow generation processes. When I disabled Hermes, the generation was as fast as on iOS.

Best,

**Comment by thekevinbrown** [comment]
We've noticed performance differences as well. On Android we use https://github.com/TomRoush/PdfBox-Android, where on iOS we use https://github.com/galkahana/PDF-Writer.

We'd welcome pull requests to improve the performance either in the upstream PdfBox-Android library, or in our bindings to it (which are fairly light).

**Comment by thekevinbrown** [comment]
Unless there's someone who's willing to chip in here, this isn't going to improve, so I'm going to go ahead and close the issue. Please feel free to create a PR to improve performance on Android.
