### ISSUE TITLE
Is there a possibility to change the font in method drawText?

### ISSUE THREAD

**Issue by KrajncJ** [Hopding/react-native-pdf-lib#5]
Getting error: 

> This font type only supports 8-bit code points

When using chars like: 

> čžšćđ

**Comment by Hopding** [comment]
Both of the underlying libraries used for manipulating PDFs can handle different fonts. However, I have not added functionality to support changing the font via the JavaScript API. This feature could certainly be added, though.

**Comment by jacargentina** [comment]
@Hopding could u accept contributions to do that? I'can try to implement it, maybe a new fontName option on the drawText options object?

**Comment by jacargentina** [comment]
@KrajncJ Done on my PR at #11

**Comment by jacargentina** [comment]
@hopding 0.2.0 supports this now?

**Comment by Hopding** [comment]
Yes, indeed it does. Thanks to @jacargentina 👍
