### ISSUE TITLE
android side issue

### ISSUE THREAD

**Issue by appa3151** [Hopding/react-native-pdf-lib#51]
if page 6 add then size issue come but ios side working
![Screenshot_20190722-192236](https://user-images.githubusercontent.com/45174248/61638163-7779b100-acb6-11e9-8577-7bc7df082a81.png)

**Comment by thekevinbrown** [comment]
Hey there, this looks like a duplicate of #46. I'll go ahead and close this, but if I'm wrong please let me know.
