### ISSUE TITLE
Looking for New Maintainer

### ISSUE THREAD

**Issue by Hopding** [Hopding/react-native-pdf-lib#52]
I created `react-native-pdf-lib` 2 years ago. At the time, there was no easy way to create or modify PDF documents in React Native environments. `react-native-pdf-lib` was meant to solve this problem. However, not long after releasing `react-native-pdf-lib`, I realized that this problem was much more widespread. There was no robust library for creating and modifying PDF documents in pure JavaScript. A few libraries existed that could partially solve the problem, but only in specific environments. 

So, I then moved on to create [`pdf-lib`](https://github.com/Hopding/pdf-lib). This library can create and modify PDFs in any JavaScript environment (React Native, browser, NodeJS, etc...) because it has no native dependencies. It is written in TypeScript and compiles to pure JavaScript. 

Developing and maintaining `pdf-lib` has consumed most of my free time. This has left me with little time and energy to develop or maintain `react-native-pdf-lib`. [Version 1.0.0](https://github.com/Hopding/pdf-lib/releases/tag/v1.0.0) of `pdf-lib` was just released last week. This version includes many improvements, including better React Native support and [examples](https://github.com/Hopding/pdf-lib#complete-examples). **At this point, `pdf-lib` can do everything that `react-native-pdf-lib` can do, and much much more.**

**I am no longer going to maintain the `react-native-pdf-lib` project. I will deprecate this project within a week or two to make this official.** If anybody is interested in stepping up to maintain this project, please leave a comment on this thread to let me know. I'd be happy to get new maintainers up to speed on the project and its architecture. We can then work out what the best approach to transfer ownership would be.

> **Many thanks to @jacargentina, @janmaennig, and @ElvisChiang for their contributions to `react-native-pdf-lib`.** Their efforts have substantially improved the project. It wouldn't be where it is today without their work!

**Comment by thekevinbrown** [comment]
@Hopding We can take this on at Tech Insite.

Our use case for this library over `pdf-lib` is we need to create high resolution, 300MB+ PDF files, and trying to do that in pure JS land is going to be a recipe for disaster.

What do you need from us as next steps?

**Comment by Hopding** [comment]
Hello @thekevinbrown! I'm glad to hear your interested in taking over maintenance of `react-native-pdf-lib`! Would you mind emailing me at `andrew.dillon.j<at>gmail.com` to discuss this further?

**Comment by thekevinbrown** [comment]
Done!

**Comment by thekevinbrown** [comment]
Everyone, I've been added as a maintainer on this library. I'll go ahead and close this issue, but if anyone else wants in, just get in touch and we'll figure it out.

**Comment by Hopding** [comment]
Yes, @thekevinbrown has agreed to step up and maintain `react-native-pdf-lib`. Many thanks to him! And, as @thekevinbrown mentioned, if anybody else would like to help out, just shoot over an email or leave a comment on this thread!

**Comment by Hopding** [comment]
@narender2031 That's great to hear! Thanks for reaching out. I'll send you an email shortly.
