### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by hoejun** [Hopding/react-native-pdf-lib#53]
Why do I get an error with the pdf button function?
[
![error](https://user-images.githubusercontent.com/45154233/63832973-e086cf80-c9ac-11e9-9414-f7c49c76639e.jpg)
](url)

**Comment by shibbyy** [comment]
@Hopding @jacargentina any help will be deeply appreciated here.

**Comment by thekevinbrown** [comment]
@shibbyy @hoejun

It looks like it's possible that React Native PDF lib isn't correctly linked into your project, so the native module isn't found at runtime. Are you sure you've linked it correctly?

**Comment by thekevinbrown** [comment]
I'm going to close this as we need more info to help here. #57 might be related as well.
