### ISSUE TITLE
are annotations supported?

### ISSUE THREAD

**Issue by gen-failure** [Hopding/react-native-pdf-lib#58]
I am currently using pdf-lib in my react-native app to open an pdf, add some simple annotations to existing pdf and save it. Is there a way how can I do the same using react-native-pdf-lib?

**Comment by thekevinbrown** [comment]
The underlying PDF implementations support this but we don't have the APIs exposed to do it yet. Would welcome a PR to do so if you're keen.

**Comment by thekevinbrown** [comment]
Going to go ahead and close this because the current answer is "no, but we could". If anyone wants to take this further they can.
