### ISSUE TITLE
Pass base64 instead of imagePath ?

### ISSUE THREAD

**Issue by unTanana** [Hopding/react-native-pdf-lib#6]
For usage like this:
.drawImage(pngPath, 'png', {
     x: 5,
     y: 25,
     width: 200,
     height: 100,
  });
Can a base64 string be passed instead of the actual path ?
Thank you!

**Comment by waltershub** [comment]
I would also really like this

**Comment by Hopding** [comment]
@unTanana Sorry for the late reply. I appreciate the feedback. I don't have as much time as I'd like to maintain this library, but I will keep your suggestion in mind.

In the meantime, you may wish to consider the solution I suggested [here](https://github.com/Hopding/react-native-pdf-lib/issues/19#issuecomment-384739753). Please note that it does involve using the [`RNFS`](https://github.com/itinance/react-native-fs) library.

**Comment by thekevinbrown** [comment]
I'm going go go ahead and close this issue as it's not going to move forward unless someone's willing to put together a PR.
