### ISSUE TITLE
TypeError: Cannot read property 'getDocumentsDirectory' of undefined

### ISSUE THREAD

**Issue by derren7532123** [Hopding/react-native-pdf-lib#60]
import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
  Button,
  TouchableOpacity
} from 'react-native';

import PDFLib, { PDFDocument, PDFPage } from 'react-native-pdf-lib';

 exportPDF=async()=> {

  const page1 = PDFPage
  .create()
  .setMediaBox(200, 200)
  .drawText('You can add text and rectangles to the PDF!', {
      x: 5,
      y: 235,
      color: '#007386',
  })
  .drawRectangle({
      x: 25,
      y: 25,
      width: 150,
      height: 150,
      color: '#FF99CC',
  })
  .drawRectangle({
      x: 75,
      y: 75,
      width: 50,
      height: 50,
      color: '#99FFCC',
  });

const jpgPath = "/Users/jorgerodriguez/Library/Developer/CoreSimulator/Devices/6DC98194-6397-49CF-80AA-D12141135B72/data/Containers/Data/Application/12D943E7-9F92-4CED-9731-6862F6AC86F8/Documents/009AA984-0B1C-421D-9DF9-1380B39737E8.jpg";
const page2 = PDFPage
  .create()
  .setMediaBox(250, 250)
  .drawText('You can add JPG images too!')
  .drawImage(jpgPath, 'jpg', {
      x: 5,
      y: 125,
      width: 200,
      height: 100,
  })

  const docsDir = await PDFLib.getDocumentsDirectory();

  const pdfPath = `${docsDir}/sample.pdf`;
PDFDocument
  .create(pdfPath)
  .addPages(page1, page2)
  .write() // Returns a promise that resolves with the PDF's path
  .then(path => {
      console.log('PDF created at: ' + path);
      // Do stuff with your shiny new PDF!
  });
}

const App: () => React$Node = () => {
  return (
    <TouchableOpacity 
    style={{flex:1,
      justifyContent: 'center',
    }}
    onPress= {()=> this.exportPDF()}
    >
      <View>
        <Text>Press ME</Text>
        </View>
      </TouchableOpacity>
  );
};

export default App;

**Comment by derren7532123** [comment]
anyone can help me solve it ?

**Comment by Quadrified** [comment]
Use RNFS or RNfetchBlob to use the file system. I couldn't get it working with getDocumentsDirectory as well.

**Comment by thekevinbrown** [comment]
Does calling anything else on PDFLib work, or is it a linking issue where the native code isn't available at runtime?

**Comment by derren7532123** [comment]
> Does calling anything else on PDFLib work, or is it a linking issue where the native code isn't available at runtime?

think is linking issue ... coz im using expo

**Comment by thekevinbrown** [comment]
Ah, yeah, Expo doesn't support custom native modules, and React Native PDF Lib isn't available on Expo. See, "How do I add custom native code to my Expo project?" here: https://docs.expo.io/versions/latest/introduction/faq/

To use this library you'd need to eject and then link the library into the project so the native code is there.

**Comment by derren7532123** [comment]
> Ah, yeah, Expo doesn't support custom native modules, and React Native PDF Lib isn't available on Expo. See, "How do I add custom native code to my Expo project?" here: https://docs.expo.io/versions/latest/introduction/faq/
> 
> To use this library you'd need to eject and then link the library into the project so the native code is there.

once i eject and i try build in xcode, it come out an error

**Comment by thekevinbrown** [comment]
What's the error?

**Comment by thekevinbrown** [comment]
Going to assume this was resolved. If there's a specific error we can help with please feel free to open a new issue.
