### ISSUE TITLE
incorrect path

### ISSUE THREAD

**Issue by kwangkim** [Hopding/react-native-pdf-lib#7]
`.create(path)` should be `.create(pdfPath)`.
```
PDFDocument
  .create(path)
  .addPages(page1, page2)
  .write() // Returns a promise that resolves with the PDF's path
  .then(path => {
    console.log('PDF created at: ' + path);
    // Do stuff with your shiny new PDF!
  });
```

**Comment by bakystefan** [comment]
use react native fs to find path, 
add in android manifest write external storage!

**Comment by Hopding** [comment]
@kwangkim Thank you! I've updated the README. Sorry for the late response.

**Comment by Hopding** [comment]
@bakystefan Not sure I understand your comment. Are you talking about a separate issue from what @kwangkim mentioned?
