### ISSUE TITLE
PDF not creating

### ISSUE THREAD

**Issue by surajsingla333** [Hopding/react-native-pdf-lib#74]
Hi, I am trying to add images in PDF and the last console i.e. `console.log('PDF created at: ' + path);` this line shows the expected result. This means that the `write()` function worked perfectly fine and I see the location where the file is created but when I go to the location on my file system I don't see any generated PDF there. Why is it happening and how can I solve it?

**Comment by thekevinbrown** [comment]
@surajsingla333 might help others that find this from a search engine if you could mention what was wrong / what the fix was.
