### ISSUE TITLE
Get page size

### ISSUE THREAD

**Issue by surajsingla333** [Hopding/react-native-pdf-lib#76]
Is there any way to get the page size? I want to put the image in center of the page irrespective of the size. Is there any way to do the same?

**Comment by thekevinbrown** [comment]
I believe you can do this with either reading the media box of a page, or calling setMediaBox.

**Comment by erick-hdz-sinergis** [comment]
> I believe you can do this with either reading the media box of a page, or calling setMediaBox.

Why can I read the media box of a page?

**Comment by thekevinbrown** [comment]
`page.mediaBox`: https://github.com/Hopding/react-native-pdf-lib/blob/master/js/src/PDFPage.js#L56
