### ISSUE TITLE
Problem saving the pdf

### ISSUE THREAD

**Issue by hidura** [Hopding/react-native-pdf-lib#8]
Hello I've this issue with the saving of the PDF give this error:
"Rejection (id: 0):
Error: /sample.pdf: open failed: EROFS (Read-only file system)
Error: /sample.pdf: open failed: EROFS (Read-only file system)
    at createErrorFromErrorData (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:7113:15)
    at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:7070:25
    at MessageQueue.__invokeCallback (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:7423:16)
    at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:7216:15
    at MessageQueue.__guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:7354:9)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:7215:13)
    at http://localhost:8081/debuggerWorker.js:72:58"

How can I solve it?

My source code.

```
/**
 * Created by diegohidalgo on 7/15/17.
 */
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
    Platform,
    TouchableOpacity,
  Text,
    Button,
  View
} from 'react-native';
import prompt from 'react-native-prompt-android';// Import from 'react-native-pdf-lib'
import PDFLib, { PDFDocument, PDFPage } from 'react-native-pdf-lib';
var Realm = require('realm');
const PrinterTest = {
  name: 'Register',
  properties: {
  }
};

// Create a PDF page with text and rectangles
const page1 = PDFPage
  .create()
  .setMediaBox(200, 200)
  .drawText('You can add text and rectangles to the PDF!', {
    x: 5,
    y: 235,
    color: '#007386',
  })
  .drawRectangle({
    x: 25,
    y: 25,
    width: 150,
    height: 150,
    color: '#FF99CC',
  })
  .drawRectangle({
    x: 75,
    y: 75,
    width: 50,
    height: 50,
    color: '#99FFCC',
  });


export default class PrintTest extends React.Component {
  static navigationOptions={
    title:'SellfastSql'
  };




  render() {
    const {navigate}=this.props.navigation;


    this.state = {
          printers:[],
          currentPrinter:false
        };
    this.componentDidMount();
    return (
      <View style={styles.container}>
        {
          this.state.printers.map(printer => (
            <TouchableOpacity key={printer.inner_mac_address} onPress={(printer) => this._connectPrinter(printer.inner_mac_address)}>
              {`device_name: ${printer.device_name}, inner_mac_address: ${printer.inner_mac_address}`}
            </TouchableOpacity>
            ))
        }
        <TouchableOpacity onPress={() => {

          const pdfPath = `/sample.pdf`;
          PDFDocument
          .create(pdfPath)
          .addPages(page1)
          .write() // Returns a promise that resolves with the PDF's path
          .then(pdfPath => {
            console.log('PDF created at: ' + pdfPath);
            // Do stuff with your shiny new PDF!
          });
        }}>
          <Text> Print Text </Text>
        </TouchableOpacity>

      </View>
    );
  }
  printTextTest = () => {
    if(this.state.currentPrinter) {
      USBPrinter.printText("<C>这是一段打印测试文字</C>\n");
    }else{
      console.log("没有设置打印机")
    }

  }

  printBillTest = () => {
    if(this.state.currentPrinter) {
      USBPrinter.printBill("<C>这是一段打印测试文字</C>");
    }else{
      console.log("没有设置打印机")
    }
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
      flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center'
  },
    register:{
      width:50
    },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

```

**Comment by CrystalRanita** [comment]
Release version device cannot write file on root path.
Here:
const pdfPath = `/sample.pdf`;
Need to change to other path.

I can create file on path: /mnt/sdcard/DCIM/Camera/sample.pdf
With Andriod AndroidManifest.xml
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
And open permission for my develop app in settings.

My function in react native js
  async _createPDF() {
    const pdf_path = '/mnt/sdcard/DCIM/Camera/sample.pdf'; 

    console.log('Write pdf file path: ', pdf_path);
    await PDFDocument
      .create(pdf_path)
      .addPages(page1, page2)
      .write() // Returns a promise that resolves with the PDF's path
      .then((path) => {
        console.log('PDF created at: ', path);
      });
  }

But I cannot get path as readme sample code:
    const docsDir = await PDFLib.getDocumentsDirectory();
    const pdf_path = `${docsDir}/sample.pdf`;

**Comment by hidura** [comment]
Thanks @CrystalRanita I works perfectlly!

**Comment by Hopding** [comment]
@CrystalRanita Thanks you for helping resolve this issue!
