### ISSUE TITLE
 where can I find the PDF file

### ISSUE THREAD

**Issue by deddyprianto** [Hopding/react-native-pdf-lib#89]
in this case i'm succesfully to make PDF FILE but it only return a path /data/user/0/files/sample.pdf , my question is 
where can I find the PDF file, i try search in the dir storage my phone(android) but i can't find any pdf file. please help me i really appreciate your suggestion

**Comment by thekevinbrown** [comment]
When it returns the path, you should be able to load the file from there, e.g. something like this:

```
<PDFPage pdfPath={`${RNFetchBlob.fs.dirs.DocumentDir}/${this.photoBook!.contentPDFPath!}`} />
```

**Comment by nathan0519** [comment]
Hi i am also facing the same problem, could you please elabourate on the steps to view the file? really appreciate your help!

**Comment by nathan0519** [comment]
What do you mean by this.photobook!.contenPDFPAth!?

**Comment by thekevinbrown** [comment]
We haven't heard from you, so I'll assume this has been resolved. If that's not the case, please open a new issue and reference this one. Thanks!
