### ISSUE TITLE
Remove yarn dependency, not needed?

### ISSUE THREAD

**Issue by jacargentina** [Hopding/react-native-pdf-lib#9]
Yarn is not needed as a dependency I think. Could it be removed? BTW, yarn from npm is giving a warning as it is not supported anymore as an npm package.

**Comment by Hopding** [comment]
@jacargentina Thank you for reporting this issue! Yes, it should be removed. It looks like the recommended way to install yarn now is [via homebrew](https://yarnpkg.com/en/docs/install).

Unfortunately I am pretty busy with other things, and am unable to prioritize work on this library right now. I'll take care of this eventually, or I'd be happy to accept a PR addressing this.

**Comment by jacargentina** [comment]
Done. On #11
