### ISSUE TITLE
My PDF is not created

### ISSUE THREAD

**Issue by Ellathet** [Hopding/react-native-pdf-lib#94]
hello, i'm using on android 11, when i go to try to create a pdf the console.log doesn't return me anything, do you know why?

` async createPDF() {
    // Create a PDF page with text and rectangles
    const page1 = PDFPage
      .create()
      .setMediaBox(200, 200)
      .drawText('You can add text and rectangles to the PDF!', {
        x: 5,
        y: 235,
        color: '#007386',
      })
      .drawRectangle({
        x: 25,
        y: 25,
        width: 150,
        height: 150,
        color: '#FF99CC',
      })
      .drawRectangle({
        x: 75,
        y: 75,
        width: 50,
        height: 50,
        color: '#99FFCC',
      });

    // Create a new PDF in your app's private Documents directory
    const docsDir = await PDFLib.getDocumentsDirectory();
    const pdfPath = `${docsDir}/sample.pdf`;
    PDFDocument
      .create(pdfPath)
      .addPages(page1)
      .write() // Returns a promise that resolves with the PDF's path
      .then((path) => {
        console.log(`PDF created at: ${path}`);
        // Do stuff with your shiny new PDF!
      });
  }`

It is called by this button:

`...
<DefaultButton
                text="Gerar Certificado"
                border={Parameters.AppColors.white}
                onPressButtonListener={() => this.createPDF()}
              />

...`

**Comment by thekevinbrown** [comment]
Are there any errors or other feedback when you run logcat?
